import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
// import "./../node_modules/bootstrap/dist/js/bootstrap"
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import store from "../features/store";
import Providers from "@/features/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pweet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <div id="modal"> </div>
        </Providers>
      </body>
    </html>
  );
}
